# Generated by Django 3.1 on 2021-01-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmwork',
            options={'verbose_name': 'кинопроизведение', 'verbose_name_plural': 'кинопроизведения'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.AlterModelOptions(
            name='genrefilmwork',
            options={'verbose_name': 'жанр фильма', 'verbose_name_plural': 'жанры фильмов'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'персона', 'verbose_name_plural': 'персоны'},
        ),
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={'verbose_name': 'участник фильма', 'verbose_name_plural': 'участники фильмов'},
        ),
    ]
