version: "3.8"

x-env: &x-env
  env_file:
    - deploys/prod.env

services:
  admin-panel:
    build: .
    volumes:
      - static:/static
    <<: *x-env
    depends_on:
      - postgres

  postgres:
    image: postgres:12.1
    restart: always
    volumes:
      - ./../../postgres_init:/docker-entrypoint-initdb.d
    <<: *x-env
    ports:
       - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:1.19.2
    restart: always
    <<: *x-env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_sites:/etc/nginx/conf.d:ro
      - static:/static
    ports:
      - 8080:80
    depends_on:
      -  admin-panel

volumes:
  static: