version: '3.8'
services:
  redis:
    restart: unless-stopped
    image: redis:6-alpine

  postgres:
    restart: unless-stopped
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres

  elasticsearch:
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2

  postgres-to-es:
    restart: unless-stopped
    build: .
    environment:
      PG_URL: postgresql://postgres:postgres@postgres/postgres
      ES_URL: http://elasticsearch:9200
      REDIS_HOST: redis